pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                sh 'npm install'       
                input {
                    message "What is this release number?"
                    ok "Submit"
                    parameters {
                        string(defaultValue: "${env.BUILD_ID}", name: 'RELEASE_NUMBER', trim: true)
                    }
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                sh 'npm run test'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Building Docker image....'
                sh "docker build -t homepage:$RELEASE_NUMBER ."
            }
        }
    }
}