pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                sh 'npm install'       
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                sh 'npm run test'
            }
        }
        stage('Deploy') {
            agent {
                dockerfile true
            }
            steps {
                echo 'Deploying....'
                sh 'node --version'
            }
        }
    }
}